### ISSUE TITLE
Review - Feature selection

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_flood#32]
- In **003_data_overview.ipynb** there is a long list of datasets but in the following ones you seem to focus only on a few variables. Could you please give details of feature selection? What variables did you decide to use and why did you not use the others?

- The reader would benefit from a look-up table to link parameter full name and short name (e.g. large scale precipitation -> lsp).

**Comment by seblehner** [comment]
Thanks for the suggestions!

> In 003_data_overview.ipynb there is a long list of datasets but in the following ones you seem to focus only on a few variables. Could you please give details of feature selection? What variables did you decide to use and why did you not use the others?

Feature selection is largely contained in **014_feature_selection.ipynb** based on a filter method (we uploaded it shortly before the review, so maybe you did not see it yet), as well as spreaded throughout other notebooks in small pieces. We will make sure to bring all parts together and will probably insert the feature selection notebook before the tests of different ML models, so that there is a logical notebook order (Might be confusing at first, but we think in the end it makes the most sense, to deliever a kind of chronological/causal ordered notebook documentation).

> The reader would benefit from a look-up table to link parameter full name and short name (e.g. large scale precipitation -> lsp).

Added short names to the tables in **003_data_overview.ipynb**.

**Comment by lkugler** [comment]
The corresponding notebooks are now 
-  [2.01_feature_selection.ipynb ](https://github.com/esowc/ml_flood/blob/master/notebooks/2_preprocessing/2.01_feature_selection.ipynb ) and 
- [1.03_data_overview.ipynb](https://github.com/esowc/ml_flood/blob/master/notebooks/1_data_download_analysis_visualization/1.03_data_overview.ipynb)
