### ISSUE TITLE
Review - Feature importance

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_flood#33]
Once you use all variables + derived variables you do not comment on feature importance. What did you learn from them? Were they all needed? How do you establish feature importance? How is the subsequent work affected by this?

**Comment by seblehner** [comment]
Although the project is already succesfully finished, for completeness sake here is additional information: Due to colinearity only a part of the features was needed. E.g. large-scale precipitation and total column water vapour had a high correlation (linearly of course), which is why we only used the former.
More comprehensive comments can be seen in the notebooks inside the **/notebooks/2_preprocessing/** folder, as well as for the best performing model (TDNN) in this notebook: **/notebooks/3_model_tests/3.05_Time-delay_neural-net.ipynb**.
