### ISSUE TITLE
Review - Spatial correlations

### ISSUE THREAD

**Issue by cvitolo** [esowc/ml_flood#34]
- Regarding the spatial correlations, in **005_visualize_your_data** and **006_data_analysis** we see spatial auto-correlation plots for convective precipitation and lsp. These plots show the effects of spatial proximity on a single variable. This is very interesting but please make your findings clearer: please comment on the radius of influence and how do you know this does not change over time and for other variables? 

- In **007_investigate_a_major_flooding_event**, the exploration of the spatial correlations across different variables is also interesting but there are only basic comments. Could you please expand the interpretation of the plots? 

- At the moment it is unclear how the exploration of spatial correlations has influenced the subsequent work, could you please elaborate on that? Did that influence the dimensionality of your problem? Please interpret the plot of spatial correlations.

**Comment by seblehner** [comment]
Although the project is already succesfully finished, for completeness sake here is what we thought while exploring this metric:

The first approach to incorporate spatial meteorological information into discharge was to plainly iterate over the points of interest (river network), while using grid points in the vicinity as additional features in the model. So the idea was to simply determine a rain-runoff relationship. Due to the large size of the catchment we were interested in, we wanted to determine a rough estimate of the radius of impact (neglecting more complex effects), to cut off all the data outside of it.
We compared different scenarios (investigate a major flooding event) to see if there is any systematic behaviour, attributable solely to the kind and/or magnitude/frequency of rain.

In the end it was not (yet) necessary, because we changed the way how we would set up the models (spatial average of the catchment for the predictor data).
Where this does in fact come a little bit into play again, is for the concept model, in which the radius of impact should give a measure on the spatial extent where predictors have significant impact on the predictand. But nevertheless, there are probably better measures than the threshold of the spatial correlation. For example the average distance a water particle covers in a day (assuming average river flow, no eddys etc.), when doing daily predictions, if rain falls inside this distance upstream.
